In [1]:
import pandas as pd
import plotly.express as px
from datetime import datetime

In [2]:
metadata_path = '../../config/metadata.tsv'
bed_targets_path = '../../config/ag-vampir.bed'
wkdir = '../..'
dataset= "my_dataset_name"
panel= 'ag-vampir'
platform='illumina'
cohort_cols = 'taxon,location'
config_path = '../../config/config.yaml'

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("max_colwidth", None)

In [3]:
# Parameters
config_path = "/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined/config/config.yaml"
metadata_path = "results/config/metadata.tsv"
bed_targets_path = "config/ag-vampir.bed"
panel = "ag-vampir"
dataset = "ag-vampir-combined"
platform = "illumina"
cohort_cols = "location,taxon,dataset_origin"
wkdir = "/mnt/user_shares/snagi/lstm_scratch/network_scratch/ampseq-agvampir-combined"

# Run information

In [4]:
time = datetime.today().strftime('%Y-%m-%d %H:%M:%S')

print(f"Dataset: {dataset}\nPanel: {panel}\nPlatform: {platform}\nCohort columns: {cohort_cols}\n\nExecution time: {time}")

Dataset: ag-vampir-combined
Panel: ag-vampir
Platform: illumina
Cohort columns: location,taxon,dataset_origin

Execution time: 2026-09-25 20:09:35

#### Reference genome

In [5]:
import yaml 
with open(config_path, 'r') as file:
    config_yml = yaml.safe_load(file)

ref_dict = {k:v for k,v in config_yml.items() if 'reference' in k}

ref_df = pd.DataFrame.from_dict(ref_dict, orient='index').reset_index()
ref_df.columns = ['reference', 'value']
ref_df

,reference,value
0,reference-name,AgamP4
1,reference-fasta,resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa
2,reference-gff3,resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3
3,reference-snpeffdb,Anopheles_gambiae

#### Panel information

In [6]:
import sys
import os
sys.path.append(os.path.join(wkdir, 'workflow/lib'))
import ampseeker as amp

panel_metadata = amp.load_bed(bed_targets_path)
contigs = panel_metadata.contig.unique()
panel_metadata

   contig     start       end amplicon_id      mutation  ref  alt
0      2L    209535    209536      Agam_1          AIM1    A    G
1      2L    927246    927247      Agam_2          AIM2    C    A
2      2L   1274352   1274353      Agam_3          AIM3    G    A
3      2L   1418209   1418210      Agam_4          AIM4    T    C
4      2L   1571928   1571929      Agam_5          AIM5    T    C
5      2L   1776347   1776348      Agam_6          AIM6    G    C
6      2L   1947573   1947574      Agam_7          AIM7    G    A
7      2L   2380981   2380982      Agam_8     Vgsc_tag1    T    C
8      2L   2381705   2381706      Agam_9     Vgsc_tag2    A    G
9      2L   2388594   2388595     Agam_10     Vgsc_tag3    G    T
10     2L   2391227   2391228     Agam_79    Vgsc_V402L    G  C,T
11     2L   2399996   2399997     Agam_11    Vgsc_D466H    G    C
12     2L   2403940   2403941     Agam_12     Vgsc_tag4    T    C
13     2L   2408422   2408423     Agam_13     Vgsc_tag5    C    T
14     2L   2408676   2408677     Agam_14     Vgsc_tag6    A    C
15     2L   2414061   2414062     Agam_15     Vgsc_tag7    A    T
16     2L   2416979   2416980     Agam_16    Vgsc_T791M    C    T
17     2L   2422650   2422651     Agam_17    Vgsc_L995S    T    C
18     2L   2422651   2422652     Agam_17    Vgsc_L995F    A    T
19     2L   2425051   2425052     Agam_18     Vgsc_tag8    G    A
20     2L   2425765   2425766     Agam_19     Vgsc_tag9    T    A
21     2L   2429616   2429617     Agam_80   Vgsc_I1527T    T    C
22     2L   2429744   2429745     Agam_20   Vgsc_N1570Y    A    T
23     2L   2429896   2429897     Agam_20   Vgsc_E1597G    A    G
24     2L   2430423   2430424     Agam_21   Vgsc_A1746S    G    T
25     2L   2430816   2430817     Agam_22   Vgsc_V1853I    G    A
26     2L   2430862   2430863     Agam_22   Vgsc_I1868T    C    T
27     2L   2430879   2430880     Agam_22   Vgsc_P1874S    C    T
28     2L   2430880   2430881     Agam_22   Vgsc_P1874L    C    T
29     2L   2431004   2431005     Agam_23          AIM8    T    C
30     2L   2431060   2431061     Agam_23   Vgsc_A1934V    C    T
31     2L   2432418   2432419     Agam_24    Vgsc_tag10    T    G
32     2L   2435580   2435581     Agam_25    Vgsc_tag11    T    A
33     2L  20288131  20288132     Agam_26   Coeae1d_tag    T    C
34     2L  25429234  25429235     Agam_27     Rdl_A296S    G    T
35     2L  25429235  25429236     Agam_27     Rdl_A296G    C    G
36     2L  25635972  25635973     Agam_28   Cyp4j5_L43F    G    A
37     2L  34073194  34073195     Agam_29     34mb_tag1    C    T
38     2L  34100757  34100758     Agam_30     34mb_tag2    A    T
39     2L  34118140  34118141     Agam_31     34mb_tag3    G    A
40     2L  34118259  34118260     Agam_31     34mb_tag4    G    A
41     2R   3492073   3492074     Agam_32    Ace1_G280S    G    A
42     2R   8368730   8368731     Agam_33          AIM9    C    A
43     2R  17854286  17854287     Agam_34         AIM10    A    C
44     2R  28492878  28492879     Agam_35   Cyp6p3_I88T    A    G
45     2R  28494246  28494247     Agam_36     Cyp6_tag1    A    C
46     2R  28497562  28497563     Agam_37     Cyp6_tag2    T    C
47     2R  28497966  28497967     Agam_38  Cyp6p4_I236M    G    C
48     2R  28498191  28498192     Agam_39     Cyp6_tag3    C    G
49     2R  28499660  28499661     Agam_40     Cyp6_tag4    G    T
50     2R  28500642  28500643     Agam_41     Cyp6_tag5    G    A
51     2R  28501398  28501399     Agam_42     Cyp6_tag6    G    A
52     2R  28502735  28502736     Agam_43     Cyp6_tag7    C    A
53     2R  28502849  28502850     Agam_43     Cyp6_tag8    C    T
54     2R  48714600  48714601     Agam_81          DSX1  NaN  NaN
55     2R  48714550  48714551     Agam_82          DSX2  NaN  NaN
56     2R  49438585  49438586     Agam_44         AIM11    T    C
57     3L     65132     65133     Agam_45         AIM12    G    T
58     3L    129050    129051     Agam_46         AIM13    C    A
59     3L    193172    193173     Agam_47         AIM14    A    G
60     3L    367247    367248     Agam_48         AIM15    C    A
61     3L    380973    380974     Agam_49         AIM16    C    A
62     3L    413507    413508     Agam_50         AIM17    G    A
63     3L  11208464  11208465     Agam_51         Tep1A    A    G
64     3L  11213954  11213955     Agam_52         Tep1B    G    T
65     3R     34263     34264     Agam_53         AIM18    G    A
66     3R     35120     35121     Agam_54         AIM19    G    A
67     3R     38160     38161     Agam_55         AIM20    G    A
68     3R     42847     42848     Agam_56         AIM21    C    A
69     3R     50589     50590     Agam_57         AIM22    G    T
70     3R     71972     71973     Agam_58         AIM23    A    C
71     3R     97616     97617     Agam_59         AIM24    A    G
72     3R   8564155   8564156     Agam_60          D7R2    G    A
73     3R  28592157  28592158     Agam_61     Gste_tag1    G    A
74     3R  28595448  28595449     Agam_62     Gste_tag2    C    T
75     3R  28598056  28598057     Agam_63    Gste_F120L    G    C
76     3R  28598061  28598062     Agam_63    Gste_L119V    G    C
77     3R  28598165  28598166     Agam_63    Gste_I114T    A    G
78     3R  28600700  28600701     Agam_64     Gste_tag3    A    G
79      X  15249653  15249654     Agam_65   Cyp9k1_tag1    A    G
80      X  15251489  15251490     Agam_66   Cyp9k1_tag2    C    T
81      X  15255320  15255321     Agam_67   Cyp9k1_tag3    A    T
82      X  18758299  18758300     Agam_68         AIM25    T    C
83      X  19631624  19631625     Agam_69         AIM26    G    C
84      X  20014695  20014696     Agam_70         AIM27    C    A
85      X  20128327  20128328     Agam_71         AIM28    T    C
86      X  20129287  20129288     Agam_72         AIM29    T    G
87      X  21721800  21721801     Agam_73         AIM30    G    C
88      X  22164042  22164043     Agam_74         AIM31    T    C
89      X  22798647  22798648     Agam_75         AIM32    C    A
90      X  23468267  23468268     Agam_76         AIM33    T    A
91      X  24229845  24229846     Agam_77         AIM34    G    A
92      X  24266727  24266728     Agam_78         AIM35    T    A

#### Input metadata

In [7]:
# load panel metadata
if metadata_path.endswith('.xlsx'):
    metadata = pd.read_excel(metadata_path, engine='openpyxl')
elif metadata_path.endswith('.tsv'):
    metadata = pd.read_csv(metadata_path, sep="\t")
elif metadata_path.endswith('.csv'):
    metadata = pd.read_csv(metadata_path, sep=",")
else:
    raise ValueError("Metadata file must be .xlsx or .csv")

metadata

,sample_id,taxon,location,country,plate,well_letter,well_number,latitude,longitude,dataset_origin
0,GH_01,NaN,Obuasi,Ghana,3,A,1,NaN,NaN,agvampir002_field
1,GH_02,NaN,Obuasi,Ghana,3,A,2,NaN,NaN,agvampir002_field
2,GH_03,NaN,Obuasi,Ghana,3,A,3,NaN,NaN,agvampir002_field
3,GH_04,NaN,Obuasi,Ghana,3,A,4,NaN,NaN,agvampir002_field
4,GH_05,NaN,Obuasi,Ghana,3,A,5,NaN,NaN,agvampir002_field
5,GH_06,NaN,Obuasi,Ghana,3,A,6,NaN,NaN,agvampir002_field
6,GH_07,NaN,Obuasi,Ghana,3,A,7,NaN,NaN,agvampir002_field
7,GH_08,NaN,Obuasi,Ghana,3,A,8,NaN,NaN,agvampir002_field
8,GH_09,NaN,Obuasi,Ghana,3,A,9,NaN,NaN,agvampir002_field
9,GH_10,NaN,Obuasi,Ghana,3,A,10,NaN,NaN,agvampir002_field
10,GH_11,NaN,Obuasi,Ghana,3,A,11,NaN,NaN,agvampir002_field
11,GH_12,NaN,Obuasi,Ghana,3,A,12,NaN,NaN,agvampir002_field
12,GH_13,NaN,Obuasi,Ghana,3,B,1,NaN,NaN,agvampir002_field
13,GH_14,NaN,Obuasi,Ghana,3,B,2,NaN,NaN,agvampir002_field
14,GH_15,NaN,Obuasi,Ghana,3,B,3,NaN,NaN,agvampir002_field
15,GH_16,NaN,Obuasi,Ghana,3,B,4,NaN,NaN,agvampir002_field
16,GH_17,NaN,Obuasi,Ghana,3,B,5,NaN,NaN,agvampir002_field
17,GH_18,NaN,Obuasi,Ghana,3,B,6,NaN,NaN,agvampir002_field
18,GH_19,NaN,Obuasi,Ghana,3,B,7,NaN,NaN,agvampir002_field
19,GH_20,NaN,Obuasi,Ghana,3,B,8,NaN,NaN,agvampir002_field
20,GH_21,NaN,Obuasi,Ghana,3,B,9,NaN,NaN,agvampir002_field
21,GH_22,NaN,Obuasi,Ghana,3,B,10,NaN,NaN,agvampir002_field
22,GH_23,NaN,Obuasi,Ghana,3,B,11,NaN,NaN,agvampir002_field
23,GH_24,NaN,Obuasi,Ghana,3,B,12,NaN,NaN,agvampir002_field
24,GH_25,NaN,Obuasi,Ghana,3,C,1,NaN,NaN,agvampir002_field
25,GH_26,NaN,Obuasi,Ghana,3,C,2,NaN,NaN,agvampir002_field
26,GH_27,NaN,Obuasi,Ghana,3,C,3,NaN,NaN,agvampir002_field
27,GH_28,NaN,Obuasi,Ghana,3,C,4,NaN,NaN,agvampir002_field
28,GH_29,NaN,Obuasi,Ghana,3,C,5,NaN,NaN,agvampir002_field
29,GH_30,NaN,Obuasi,Ghana,3,C,6,NaN,NaN,agvampir002_field
30,GH_31,NaN,Obuasi,Ghana,3,C,7,NaN,NaN,agvampir002_field
31,GH_32,NaN,Obuasi,Ghana,3,C,8,NaN,NaN,agvampir002_field
32,GH_33,NaN,Obuasi,Ghana,3,C,9,NaN,NaN,agvampir002_field
33,GH_34,NaN,Obuasi,Ghana,3,C,10,NaN,NaN,agvampir002_field
34,GH_35,NaN,Obuasi,Ghana,3,C,11,NaN,NaN,agvampir002_field
35,GH_36,NaN,Obuasi,Ghana,3,C,12,NaN,NaN,agvampir002_field
36,GH_37,NaN,Obuasi,Ghana,3,D,1,NaN,NaN,agvampir002_field
37,GH_38,NaN,Obuasi,Ghana,3,D,2,NaN,NaN,agvampir002_field
38,GH_39,NaN,Obuasi,Ghana,3,D,3,NaN,NaN,agvampir002_field
39,GH_40_low_vol,NaN,Obuasi,Ghana,3,D,4,NaN,NaN,agvampir002_field
40,GH_41,NaN,Obuasi,Ghana,3,D,5,NaN,NaN,agvampir002_field
41,GH_42,NaN,Obuasi,Ghana,3,D,6,NaN,NaN,agvampir002_field
42,GH_43,NaN,Obuasi,Ghana,3,D,7,NaN,NaN,agvampir002_field
43,GH_44,NaN,Obuasi,Ghana,3,D,8,NaN,NaN,agvampir002_field
44,GH_45,NaN,Obuasi,Ghana,3,D,9,NaN,NaN,agvampir002_field
45,GH_46,NaN,Obuasi,Ghana,3,D,10,NaN,NaN,agvampir002_field
46,GH_47,NaN,Obuasi,Ghana,3,D,11,NaN,NaN,agvampir002_field
47,GH_48,NaN,Obuasi,Ghana,3,D,12,NaN,NaN,agvampir002_field
48,GH_49,NaN,Obuasi,Ghana,3,E,1,NaN,NaN,agvampir002_field
49,GH_50,NaN,Obuasi,Ghana,3,E,2,NaN,NaN,agvampir002_field
50,GH_51,NaN,Obuasi,Ghana,3,E,3,NaN,NaN,agvampir002_field
51,GH_52,NaN,Obuasi,Ghana,3,E,4,NaN,NaN,agvampir002_field
52,GH_53,NaN,Obuasi,Ghana,3,E,5,NaN,NaN,agvampir002_field
53,GH_54,NaN,Obuasi,Ghana,3,E,6,NaN,NaN,agvampir002_field
54,GH_55,NaN,Obuasi,Ghana,3,E,7,NaN,NaN,agvampir002_field
55,GH_56,NaN,Obuasi,Ghana,3,E,8,NaN,NaN,agvampir002_field
56,GH_57,NaN,Obuasi,Ghana,3,E,9,NaN,NaN,agvampir002_field
57,GH_58,NaN,Obuasi,Ghana,3,E,10,NaN,NaN,agvampir002_field
58,GH_59,NaN,Obuasi,Ghana,3,E,11,NaN,NaN,agvampir002_field
59,GH_60,NaN,Obuasi,Ghana,3,E,12,NaN,NaN,agvampir002_field
60,GH_61,NaN,Obuasi,Ghana,3,F,1,NaN,NaN,agvampir002_field
61,GH_62,NaN,Obuasi,Ghana,3,F,2,NaN,NaN,agvampir002_field
62,GH_63,NaN,Obuasi,Ghana,3,F,3,NaN,NaN,agvampir002_field
63,GH_64,NaN,Obuasi,Ghana,3,F,4,NaN,NaN,agvampir002_field
64,GH_65_low_vol,NaN,Obuasi,Ghana,3,F,5,NaN,NaN,agvampir002_field
65,GH_66,NaN,Obuasi,Ghana,3,F,6,NaN,NaN,agvampir002_field
66,GH_67,NaN,Obuasi,Ghana,3,F,7,NaN,NaN,agvampir002_field
67,GH_68,NaN,Obuasi,Ghana,3,F,8,NaN,NaN,agvampir002_field
68,GH_69,NaN,Obuasi,Ghana,3,F,9,NaN,NaN,agvampir002_field
69,GH_70,NaN,Obuasi,Ghana,3,F,10,NaN,NaN,agvampir002_field
70,GH_71,NaN,Obuasi,Ghana,3,F,11,NaN,NaN,agvampir002_field
71,GH_72,NaN,Obuasi,Ghana,3,F,12,NaN,NaN,agvampir002_field
72,GH_73,NaN,Obuasi,Ghana,3,G,1,NaN,NaN,agvampir002_field
73,GH_74,NaN,Obuasi,Ghana,3,G,2,NaN,NaN,agvampir002_field
74,GH_75,NaN,Obuasi,Ghana,3,G,3,NaN,NaN,agvampir002_field
75,GH_76,NaN,Obuasi,Ghana,3,G,4,NaN,NaN,agvampir002_field
76,GH_77,NaN,Obuasi,Ghana,3,G,5,NaN,NaN,agvampir002_field
77,GH_78,NaN,Obuasi,Ghana,3,G,6,NaN,NaN,agvampir002_field
78,GH_79,NaN,Obuasi,Ghana,3,G,7,NaN,NaN,agvampir002_field
79,GH_80_low_vol,NaN,Obuasi,Ghana,3,G,8,NaN,NaN,agvampir002_field
80,GH_81,NaN,Obuasi,Ghana,3,G,9,NaN,NaN,agvampir002_field
81,GH_82,NaN,Obuasi,Ghana,3,G,10,NaN,NaN,agvampir002_field
82,GH_83,NaN,Obuasi,Ghana,3,G,11,NaN,NaN,agvampir002_field
83,GH_84,NaN,Obuasi,Ghana,3,G,12,NaN,NaN,agvampir002_field
84,GH_85,NaN,Obuasi,Ghana,3,H,1,NaN,NaN,agvampir002_field
85,GH_86,NaN,Obuasi,Ghana,3,H,2,NaN,NaN,agvampir002_field
86,GH_87,NaN,Obuasi,Ghana,3,H,3,NaN,NaN,agvampir002_field
87,GH_88,NaN,Obuasi,Ghana,3,H,4,NaN,NaN,agvampir002_field
88,GH_89,NaN,Obuasi,Ghana,3,H,5,NaN,NaN,agvampir002_field
89,GH_90,NaN,Obuasi,Ghana,3,H,6,NaN,NaN,agvampir002_field
90,GH_91,NaN,Obuasi,Ghana,3,H,7,NaN,NaN,agvampir002_field
91,GH_92,NaN,Obuasi,Ghana,3,H,8,NaN,NaN,agvampir002_field
92,GH_93,NaN,Obuasi,Ghana,3,H,9,NaN,NaN,agvampir002_field
93,GH_94,NaN,Obuasi,Ghana,3,H,10,NaN,NaN,agvampir002_field
94,GH_95,NaN,Obuasi,Ghana,3,H,11,NaN,NaN,agvampir002_field
95,GH_Negative,NaN,Obuasi,Ghana,3,H,12,NaN,NaN,agvampir002_field
96,GM_01,NaN,Gambia_URR,Gambia,8,A,1,NaN,NaN,agvampir002_field
97,GM_02,NaN,Gambia_URR,Gambia,8,A,2,NaN,NaN,agvampir002_field
98,GM_03,NaN,Gambia_URR,Gambia,8,A,3,NaN,NaN,agvampir002_field
99,GM_04,NaN,Gambia_URR,Gambia,8,A,4,NaN,NaN,agvampir002_field
100,GM_05,NaN,Gambia_URR,Gambia,8,A,5,NaN,NaN,agvampir002_field
101,GM_06,NaN,Gambia_URR,Gambia,8,A,6,NaN,NaN,agvampir002_field
102,GM_07,NaN,Gambia_URR,Gambia,8,A,7,NaN,NaN,agvampir002_field
103,GM_08,NaN,Gambia_URR,Gambia,8,A,8,NaN,NaN,agvampir002_field
104,GM_09,NaN,Gambia_URR,Gambia,8,A,9,NaN,NaN,agvampir002_field
105,GM_10,NaN,Gambia_URR,Gambia,8,A,10,NaN,NaN,agvampir002_field
106,GM_11,NaN,Gambia_URR,Gambia,8,A,11,NaN,NaN,agvampir002_field
107,GM_12,NaN,Gambia_URR,Gambia,8,A,12,NaN,NaN,agvampir002_field
108,GM_13,NaN,Gambia_URR,Gambia,8,B,1,NaN,NaN,agvampir002_field
109,GM_14,NaN,Gambia_URR,Gambia,8,B,2,NaN,NaN,agvampir002_field
110,GM_15,NaN,Gambia_URR,Gambia,8,B,3,NaN,NaN,agvampir002_field
111,GM_16,NaN,Gambia_URR,Gambia,8,B,4,NaN,NaN,agvampir002_field
112,GM_17,NaN,Gambia_URR,Gambia,8,B,5,NaN,NaN,agvampir002_field
113,GM_18,NaN,Gambia_URR,Gambia,8,B,6,NaN,NaN,agvampir002_field
114,GM_19,NaN,Gambia_URR,Gambia,8,B,7,NaN,NaN,agvampir002_field
115,GM_20,NaN,Gambia_URR,Gambia,8,B,8,NaN,NaN,agvampir002_field
116,GM_21,NaN,Gambia_URR,Gambia,8,B,9,NaN,NaN,agvampir002_field
117,GM_22,NaN,Gambia_URR,Gambia,8,B,10,NaN,NaN,agvampir002_field
118,GM_23,NaN,Gambia_URR,Gambia,8,B,11,NaN,NaN,agvampir002_field
119,GM_24,NaN,Gambia_URR,Gambia,8,B,12,NaN,NaN,agvampir002_field
120,GM_25,NaN,Gambia_URR,Gambia,8,C,1,NaN,NaN,agvampir002_field
121,GM_26,NaN,Gambia_URR,Gambia,8,C,2,NaN,NaN,agvampir002_field
122,GM_27,NaN,Gambia_URR,Gambia,8,C,3,NaN,NaN,agvampir002_field
123,GM_28,NaN,Gambia_URR,Gambia,8,C,4,NaN,NaN,agvampir002_field
124,GM_29,NaN,Gambia_URR,Gambia,8,C,5,NaN,NaN,agvampir002_field
125,GM_30,NaN,Gambia_URR,Gambia,8,C,6,NaN,NaN,agvampir002_field
126,GM_31,NaN,Gambia_URR,Gambia,8,C,7,NaN,NaN,agvampir002_field
127,GM_32,NaN,Gambia_URR,Gambia,8,C,8,NaN,NaN,agvampir002_field
128,GM_33,NaN,Gambia_URR,Gambia,8,C,9,NaN,NaN,agvampir002_field
129,GM_34,NaN,Gambia_URR,Gambia,8,C,10,NaN,NaN,agvampir002_field
130,GM_35,NaN,Gambia_URR,Gambia,8,C,11,NaN,NaN,agvampir002_field
131,GM_36,NaN,Gambia_URR,Gambia,8,C,12,NaN,NaN,agvampir002_field
132,GM_37,NaN,Gambia_URR,Gambia,8,D,1,NaN,NaN,agvampir002_field
133,GM_38,NaN,Gambia_URR,Gambia,8,D,2,NaN,NaN,agvampir002_field
134,GM_39,NaN,Gambia_URR,Gambia,8,D,3,NaN,NaN,agvampir002_field
135,GM_40,NaN,Gambia_URR,Gambia,8,D,4,NaN,NaN,agvampir002_field
136,GM_41,NaN,Gambia_URR,Gambia,8,D,5,NaN,NaN,agvampir002_field
137,GM_42,NaN,Gambia_URR,Gambia,8,D,6,NaN,NaN,agvampir002_field
138,GM_43,NaN,Gambia_URR,Gambia,8,D,7,NaN,NaN,agvampir002_field
139,GM_44,NaN,Gambia_URR,Gambia,8,D,8,NaN,NaN,agvampir002_field
140,GM_45,NaN,Gambia_URR,Gambia,8,D,9,NaN,NaN,agvampir002_field
141,GM_46,NaN,Gambia_URR,Gambia,8,D,10,NaN,NaN,agvampir002_field
142,GM_47,NaN,Gambia_URR,Gambia,8,D,11,NaN,NaN,agvampir002_field
143,GM_48,NaN,Gambia_URR,Gambia,8,D,12,NaN,NaN,agvampir002_field
144,GM_49,NaN,Gambia_URR,Gambia,8,E,1,NaN,NaN,agvampir002_field
145,GM_50,NaN,Gambia_URR,Gambia,8,E,2,NaN,NaN,agvampir002_field
146,GM_51,NaN,Gambia_URR,Gambia,8,E,3,NaN,NaN,agvampir002_field
147,GM_52,NaN,Gambia_URR,Gambia,8,E,4,NaN,NaN,agvampir002_field
148,GM_53,NaN,Gambia_URR,Gambia,8,E,5,NaN,NaN,agvampir002_field
149,GM_54,NaN,Gambia_URR,Gambia,8,E,6,NaN,NaN,agvampir002_field
150,GM_55,NaN,Gambia_URR,Gambia,8,E,7,NaN,NaN,agvampir002_field
151,GM_56,NaN,Gambia_URR,Gambia,8,E,8,NaN,NaN,agvampir002_field
152,GM_57,NaN,Gambia_URR,Gambia,8,E,9,NaN,NaN,agvampir002_field
153,GM_58,NaN,Gambia_URR,Gambia,8,E,10,NaN,NaN,agvampir002_field
154,GM_59,NaN,Gambia_URR,Gambia,8,E,11,NaN,NaN,agvampir002_field
155,GM_60,NaN,Gambia_URR,Gambia,8,E,12,NaN,NaN,agvampir002_field
156,GM_61,NaN,Gambia_URR,Gambia,8,F,1,NaN,NaN,agvampir002_field
157,GM_62,NaN,Gambia_URR,Gambia,8,F,2,NaN,NaN,agvampir002_field
158,GM_63,NaN,Gambia_URR,Gambia,8,F,3,NaN,NaN,agvampir002_field
159,GM_64,NaN,Gambia_URR,Gambia,8,F,4,NaN,NaN,agvampir002_field
160,GM_65,NaN,Gambia_URR,Gambia,8,F,5,NaN,NaN,agvampir002_field
161,GM_66,NaN,Gambia_URR,Gambia,8,F,6,NaN,NaN,agvampir002_field
162,GM_67,NaN,Gambia_URR,Gambia,8,F,7,NaN,NaN,agvampir002_field
163,GM_68,NaN,Gambia_URR,Gambia,8,F,8,NaN,NaN,agvampir002_field
164,GM_69,NaN,Gambia_URR,Gambia,8,F,9,NaN,NaN,agvampir002_field
165,GM_70,NaN,Gambia_URR,Gambia,8,F,10,NaN,NaN,agvampir002_field
166,GM_71,NaN,Gambia_URR,Gambia,8,F,11,NaN,NaN,agvampir002_field
167,GM_72,NaN,Gambia_URR,Gambia,8,F,12,NaN,NaN,agvampir002_field
168,GM_73,NaN,Gambia_URR,Gambia,8,G,1,NaN,NaN,agvampir002_field
169,GM_74,NaN,Gambia_URR,Gambia,8,G,2,NaN,NaN,agvampir002_field
170,GM_75,NaN,Gambia_URR,Gambia,8,G,3,NaN,NaN,agvampir002_field
171,GM_76,NaN,Gambia_URR,Gambia,8,G,4,NaN,NaN,agvampir002_field
172,GM_77,NaN,Gambia_URR,Gambia,8,G,5,NaN,NaN,agvampir002_field
173,GM_78,NaN,Gambia_URR,Gambia,8,G,6,NaN,NaN,agvampir002_field
174,GM_79,NaN,Gambia_URR,Gambia,8,G,7,NaN,NaN,agvampir002_field
175,GM_80,NaN,Gambia_URR,Gambia,8,G,8,NaN,NaN,agvampir002_field
176,GM_81,NaN,Gambia_URR,Gambia,8,G,9,NaN,NaN,agvampir002_field
177,GM_82,NaN,Gambia_URR,Gambia,8,G,10,NaN,NaN,agvampir002_field
178,GM_83,NaN,Gambia_URR,Gambia,8,G,11,NaN,NaN,agvampir002_field
179,GM_84,NaN,Gambia_URR,Gambia,8,G,12,NaN,NaN,agvampir002_field
180,GM_85,NaN,Gambia_URR,Gambia,8,H,1,NaN,NaN,agvampir002_field
181,GM_86,NaN,Gambia_URR,Gambia,8,H,2,NaN,NaN,agvampir002_field
182,GM_87,NaN,Gambia_URR,Gambia,8,H,3,NaN,NaN,agvampir002_field
183,GM_88,NaN,Gambia_URR,Gambia,8,H,4,NaN,NaN,agvampir002_field
184,GM_89,NaN,Gambia_URR,Gambia,8,H,5,NaN,NaN,agvampir002_field
185,GM_90,NaN,Gambia_URR,Gambia,8,H,6,NaN,NaN,agvampir002_field
186,GM_91,NaN,Gambia_URR,Gambia,8,H,7,NaN,NaN,agvampir002_field
187,GM_92,NaN,Gambia_URR,Gambia,8,H,8,NaN,NaN,agvampir002_field
188,GM_93,NaN,Gambia_URR,Gambia,8,H,9,NaN,NaN,agvampir002_field
189,GM_94,NaN,Gambia_URR,Gambia,8,H,10,NaN,NaN,agvampir002_field
190,GM_95,NaN,Gambia_URR,Gambia,8,H,11,NaN,NaN,agvampir002_field
191,GM_96,NaN,Gambia_URR,Gambia,8,H,12,NaN,NaN,agvampir002_field
192,VK7_dead_01,coluzzii,VK7,Burkina Faso,10,A,1,NaN,NaN,agvampir002_field
193,VK7_dead_02,coluzzii,VK7,Burkina Faso,10,A,2,NaN,NaN,agvampir002_field
194,VK7_dead_03,coluzzii,VK7,Burkina Faso,10,A,3,NaN,NaN,agvampir002_field
195,VK7_dead_04,coluzzii,VK7,Burkina Faso,10,A,4,NaN,NaN,agvampir002_field
196,VK7_dead_05,coluzzii,VK7,Burkina Faso,10,A,5,NaN,NaN,agvampir002_field
197,VK7_dead_06,coluzzii,VK7,Burkina Faso,10,A,6,NaN,NaN,agvampir002_field
198,VK7_alive_01,coluzzii,VK7,Burkina Faso,10,A,7,NaN,NaN,agvampir002_field
199,VK7_alive_02,coluzzii,VK7,Burkina Faso,10,A,8,NaN,NaN,agvampir002_field
200,VK7_alive_03,coluzzii,VK7,Burkina Faso,10,A,9,NaN,NaN,agvampir002_field
201,VK7_alive_04,coluzzii,VK7,Burkina Faso,10,A,10,NaN,NaN,agvampir002_field
202,VK7_alive_05,coluzzii,VK7,Burkina Faso,10,A,11,NaN,NaN,agvampir002_field
203,VK7_alive_06,coluzzii,VK7,Burkina Faso,10,A,12,NaN,NaN,agvampir002_field
204,VK7_dead_07,coluzzii,VK7,Burkina Faso,10,B,1,NaN,NaN,agvampir002_field
205,VK7_dead_08,coluzzii,VK7,Burkina Faso,10,B,2,NaN,NaN,agvampir002_field
206,VK7_dead_09,coluzzii,VK7,Burkina Faso,10,B,3,NaN,NaN,agvampir002_field
207,VK7_dead_10,coluzzii,VK7,Burkina Faso,10,B,4,NaN,NaN,agvampir002_field
208,VK7_dead_11,coluzzii,VK7,Burkina Faso,10,B,5,NaN,NaN,agvampir002_field
209,VK7_dead_12,coluzzii,VK7,Burkina Faso,10,B,6,NaN,NaN,agvampir002_field
210,VK7_alive_07,coluzzii,VK7,Burkina Faso,10,B,7,NaN,NaN,agvampir002_field
211,VK7_alive_08,coluzzii,VK7,Burkina Faso,10,B,8,NaN,NaN,agvampir002_field
212,VK7_alive_09,coluzzii,VK7,Burkina Faso,10,B,9,NaN,NaN,agvampir002_field
213,VK7_alive_10,coluzzii,VK7,Burkina Faso,10,B,10,NaN,NaN,agvampir002_field
214,VK7_alive_11,coluzzii,VK7,Burkina Faso,10,B,11,NaN,NaN,agvampir002_field
215,VK7_alive_12,coluzzii,VK7,Burkina Faso,10,B,12,NaN,NaN,agvampir002_field
216,VK7_dead_13,coluzzii,VK7,Burkina Faso,10,C,1,NaN,NaN,agvampir002_field
217,VK7_dead_14,coluzzii,VK7,Burkina Faso,10,C,2,NaN,NaN,agvampir002_field
218,VK7_dead_15,coluzzii,VK7,Burkina Faso,10,C,3,NaN,NaN,agvampir002_field
219,VK7_dead_16,coluzzii,VK7,Burkina Faso,10,C,4,NaN,NaN,agvampir002_field
220,VK7_dead_17,coluzzii,VK7,Burkina Faso,10,C,5,NaN,NaN,agvampir002_field
221,VK7_dead_04_dil,coluzzii,VK7,Burkina Faso,10,C,6,NaN,NaN,agvampir002_field
222,VK7_alive_13,coluzzii,VK7,Burkina Faso,10,C,7,NaN,NaN,agvampir002_field
223,VK7_alive_14,coluzzii,VK7,Burkina Faso,10,C,8,NaN,NaN,agvampir002_field
224,VK7_alive_15,coluzzii,VK7,Burkina Faso,10,C,9,NaN,NaN,agvampir002_field
225,VK7_alive_16,coluzzii,VK7,Burkina Faso,10,C,10,NaN,NaN,agvampir002_field
226,VK7_alive_17,coluzzii,VK7,Burkina Faso,10,C,11,NaN,NaN,agvampir002_field
227,VK7_alive_18,coluzzii,VK7,Burkina Faso,10,C,12,NaN,NaN,agvampir002_field
228,VK7_dead_18,coluzzii,VK7,Burkina Faso,10,D,1,NaN,NaN,agvampir002_field
229,VK7_dead_19,coluzzii,VK7,Burkina Faso,10,D,2,NaN,NaN,agvampir002_field
230,VK7_dead_20,coluzzii,VK7,Burkina Faso,10,D,3,NaN,NaN,agvampir002_field
231,VK7_dead_21,coluzzii,VK7,Burkina Faso,10,D,4,NaN,NaN,agvampir002_field
232,VK7_dead_22,coluzzii,VK7,Burkina Faso,10,D,5,NaN,NaN,agvampir002_field
233,VK7_dead_10_dil,coluzzii,VK7,Burkina Faso,10,D,6,NaN,NaN,agvampir002_field
234,VK7_alive_19,coluzzii,VK7,Burkina Faso,10,D,7,NaN,NaN,agvampir002_field
235,VK7_alive_20,coluzzii,VK7,Burkina Faso,10,D,8,NaN,NaN,agvampir002_field
236,VK7_alive_21,coluzzii,VK7,Burkina Faso,10,D,9,NaN,NaN,agvampir002_field
237,VK7_alive_22,coluzzii,VK7,Burkina Faso,10,D,10,NaN,NaN,agvampir002_field
238,VK7_alive_23,coluzzii,VK7,Burkina Faso,10,D,11,NaN,NaN,agvampir002_field
239,VK7_alive_24,coluzzii,VK7,Burkina Faso,10,D,12,NaN,NaN,agvampir002_field
240,VK7_dead_23,coluzzii,VK7,Burkina Faso,10,E,1,NaN,NaN,agvampir002_field
241,VK7_dead_24,coluzzii,VK7,Burkina Faso,10,E,2,NaN,NaN,agvampir002_field
242,VK7_dead_25,coluzzii,VK7,Burkina Faso,10,E,3,NaN,NaN,agvampir002_field
243,VK7_dead_26,coluzzii,VK7,Burkina Faso,10,E,4,NaN,NaN,agvampir002_field
244,VK7_dead_27,coluzzii,VK7,Burkina Faso,10,E,5,NaN,NaN,agvampir002_field
245,VK7_dead_16_dil,coluzzii,VK7,Burkina Faso,10,E,6,NaN,NaN,agvampir002_field
246,VK7_alive_25,coluzzii,VK7,Burkina Faso,10,E,7,NaN,NaN,agvampir002_field
247,VK7_alive_26,coluzzii,VK7,Burkina Faso,10,E,8,NaN,NaN,agvampir002_field
248,VK7_alive_27,coluzzii,VK7,Burkina Faso,10,E,9,NaN,NaN,agvampir002_field
249,VK7_alive_28,coluzzii,VK7,Burkina Faso,10,E,10,NaN,NaN,agvampir002_field
250,VK7_alive_29,coluzzii,VK7,Burkina Faso,10,E,11,NaN,NaN,agvampir002_field
251,VK7_alive_30,coluzzii,VK7,Burkina Faso,10,E,12,NaN,NaN,agvampir002_field
252,VK7_dead_28,coluzzii,VK7,Burkina Faso,10,F,1,NaN,NaN,agvampir002_field
253,VK7_dead_29,coluzzii,VK7,Burkina Faso,10,F,2,NaN,NaN,agvampir002_field
254,VK7_dead_30,coluzzii,VK7,Burkina Faso,10,F,3,NaN,NaN,agvampir002_field
255,VK7_dead_31,coluzzii,VK7,Burkina Faso,10,F,4,NaN,NaN,agvampir002_field
256,VK7_dead_32,coluzzii,VK7,Burkina Faso,10,F,5,NaN,NaN,agvampir002_field
257,VK7_dead_22_dil,coluzzii,VK7,Burkina Faso,10,F,6,NaN,NaN,agvampir002_field
258,VK7_alive_31,coluzzii,VK7,Burkina Faso,10,F,7,NaN,NaN,agvampir002_field
259,VK7_alive_32,coluzzii,VK7,Burkina Faso,10,F,8,NaN,NaN,agvampir002_field
260,VK7_alive_33,coluzzii,VK7,Burkina Faso,10,F,9,NaN,NaN,agvampir002_field
261,VK7_alive_34,coluzzii,VK7,Burkina Faso,10,F,10,NaN,NaN,agvampir002_field
262,VK7_alive_35,coluzzii,VK7,Burkina Faso,10,F,11,NaN,NaN,agvampir002_field
263,VK7_alive_36,coluzzii,VK7,Burkina Faso,10,F,12,NaN,NaN,agvampir002_field
264,VK7_dead_33,coluzzii,VK7,Burkina Faso,10,G,1,NaN,NaN,agvampir002_field
265,VK7_dead_34,coluzzii,VK7,Burkina Faso,10,G,2,NaN,NaN,agvampir002_field
266,VK7_dead_35,coluzzii,VK7,Burkina Faso,10,G,3,NaN,NaN,agvampir002_field
267,VK7_dead_36,coluzzii,VK7,Burkina Faso,10,G,4,NaN,NaN,agvampir002_field
268,VK7_dead_37,coluzzii,VK7,Burkina Faso,10,G,5,NaN,NaN,agvampir002_field
269,VK7_dead_28_dil,coluzzii,VK7,Burkina Faso,10,G,6,NaN,NaN,agvampir002_field
270,VK7_alive_37,coluzzii,VK7,Burkina Faso,10,G,7,NaN,NaN,agvampir002_field
271,VK7_alive_38,coluzzii,VK7,Burkina Faso,10,G,8,NaN,NaN,agvampir002_field
272,VK7_alive_39,coluzzii,VK7,Burkina Faso,10,G,9,NaN,NaN,agvampir002_field
273,VK7_alive_40,coluzzii,VK7,Burkina Faso,10,G,10,NaN,NaN,agvampir002_field
274,VK7_alive_41,coluzzii,VK7,Burkina Faso,10,G,11,NaN,NaN,agvampir002_field
275,VK7_alive_42,coluzzii,VK7,Burkina Faso,10,G,12,NaN,NaN,agvampir002_field
276,VK7_dead_38,coluzzii,VK7,Burkina Faso,10,H,1,NaN,NaN,agvampir002_field
277,VK7_dead_39,coluzzii,VK7,Burkina Faso,10,H,2,NaN,NaN,agvampir002_field
278,VK7_dead_40,coluzzii,VK7,Burkina Faso,10,H,3,NaN,NaN,agvampir002_field
279,VK7_dead_41,coluzzii,VK7,Burkina Faso,10,H,4,NaN,NaN,agvampir002_field
280,VK7_dead_42,coluzzii,VK7,Burkina Faso,10,H,5,NaN,NaN,agvampir002_field
281,VK7_dead_34_dil,coluzzii,VK7,Burkina Faso,10,H,6,NaN,NaN,agvampir002_field
282,VK7_alive_43,coluzzii,VK7,Burkina Faso,10,H,7,NaN,NaN,agvampir002_field
283,VK7_alive_44,coluzzii,VK7,Burkina Faso,10,H,8,NaN,NaN,agvampir002_field
284,VK7_alive_45,coluzzii,VK7,Burkina Faso,10,H,9,NaN,NaN,agvampir002_field
285,VK7_alive_46,coluzzii,VK7,Burkina Faso,10,H,10,NaN,NaN,agvampir002_field
286,VK7_alive_47,coluzzii,VK7,Burkina Faso,10,H,11,NaN,NaN,agvampir002_field
287,VK7_Negative,NaN,VK7,Burkina Faso,10,H,12,NaN,NaN,agvampir002_field
288,Siaya_Delta_Dead_01,gambiae,Siaya,Kenya,12,A,1,NaN,NaN,agvampir002_field
289,Siaya_Delta_Dead_02,gambiae,Siaya,Kenya,12,A,2,NaN,NaN,agvampir002_field
290,Siaya_Delta_Dead_03,gambiae,Siaya,Kenya,12,A,3,NaN,NaN,agvampir002_field
291,Siaya_Delta_Dead_04,gambiae,Siaya,Kenya,12,A,4,NaN,NaN,agvampir002_field
292,Siaya_Delta_Dead_05,gambiae,Siaya,Kenya,12,A,5,NaN,NaN,agvampir002_field
293,Siaya_Delta_Dead_06,gambiae,Siaya,Kenya,12,A,6,NaN,NaN,agvampir002_field
294,Siaya_Delta_Dead_07,gambiae,Siaya,Kenya,12,A,7,NaN,NaN,agvampir002_field
295,Siaya_Delta_Dead_08,gambiae,Siaya,Kenya,12,A,8,NaN,NaN,agvampir002_field
296,Siaya_Delta_Dead_09,gambiae,Siaya,Kenya,12,A,9,NaN,NaN,agvampir002_field
297,Siaya_Delta_Dead_10,gambiae,Siaya,Kenya,12,A,10,NaN,NaN,agvampir002_field